### ISSUE TITLE
Song title <a> is too short

### ISSUE THREAD

**Issue by brinox** [jez500/chorus#102]
I'm using Chorus with Firefox 34.0.5 on Linux. In my webinterface the song title <a> element's width is too short as seen in this screenshot:

![title-anchor-bug](https://cloud.githubusercontent.com/assets/2724840/5682710/49d1b8f4-9822-11e4-88de-230da27165ad.png)

Sometimes it even has width 0 and displays nothing. I found out that removing the `overflow: hidden` css rule on the `playing-song-title` class fixed it. Is it only me having that issue?

**Comment by alpha-ninja** [comment]
I previously reported this. #65

**Comment by brinox** [comment]
Sorry for the duplicate, didn't recognize it.
