### ISSUE TITLE
add extra extension to addon.xml

### ISSUE THREAD

**Issue by MartijnKaijser** [jez500/chorus#106]
We will introduce a change in the extension type for webinterfaces:
point="xbmc.webinterface"
https://github.com/xbmc/xbmc/pull/6396/files

please duplicate the current extension point and use xbmc.webinterface as the second one.
I will already push a minor bump to 0.3.9 in our official Kodi repo which will contain this update.
I see you already have 0.3.9 here so in order to update repo please bump your version when you request an update.

See
https://github.com/xbmc/repo-webinterfaces/commit/6ba5a571cb821ada93288f7aa6730db66ad5b9bc

**Comment by jez500** [comment]
Thanks @MartijnKaijser will do, 
To clarify... It will now have 2 extension points? I guess one for old versions the other for new?
I actually have a huge update on its way which I need to talk to you about but will wait until it is complete (not long to go).

**Comment by MartijnKaijser** [comment]
Yes two extensions. For 15.0 there will only be one left. Having double now is just so you can use in the old version as well
