### ISSUE TITLE
Add hability to show subtitles from web streaming

### ISSUE THREAD

**Issue by p2kmgcl** [jez500/chorus#21]

**Comment by phadric** [comment]
well if there is a way to get the filenames its quite easy to display subtitles....im currently using this:
https://github.com/phadric/chorus/commit/0e93adf4c13daf2fc8a6e74b8bd84b15ee6f2e84 but it would be nice to get a list of available subtitles from xbmc directly including the languages...

**Comment by joshlopes** [comment]
Other way to grab subtitles outside without being dependable on XBMC would be using a JS api from Opensubtitles for example: https://github.com/aetheon/node-opensubtitles-client
