### ISSUE TITLE
View live TV and/or recordings

### ISSUE THREAD

**Issue by danepowell** [jez500/chorus#23]
Live TV is now a first-class citizen of XBMC, alongside movies, TV shows, and music. It would be nice if this were reflected in the web interface, by being able to view live tv or at least recordings natively. The only way to view recordings right now is to add them as a files directory, which makes them hard to find if you don't know where to look.

**Comment by ninovanhooff** [comment]
I don't see the option to select a channel in Version 0.3.10? Using Kodi 16
