### ISSUE TITLE
Now Playing field empty for LiveTV (Nothing Playing)

### ISSUE THREAD

**Issue by schumi2004** [jez500/chorus#38]
The Now Playing field shows Nothing Playing for LiveTV streams.
It does display duration.
I'm running webinterface on OpenELEC (x86_64) Gotham 13 beta 1

**Comment by atharmian** [comment]
Similar issue.

Running Jarvis v16 Kodi. Configured Chorus on it, and clicked on RT channel within iVue2 RV Guide. Then opened Chorus in Chrome browser.
Can see bottom notification about RT channel, but cannot see playback ...no picture/ stream.
I'm fact I have been unable to stream any content ( don't have any recordings, merely trying to stream live IPTV content to Chrome browser via Chorus.)

Any fixes? Should I try the new Chorus 2?  ( also sent email to you last night :) )
